/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#f3e481",
        "surface-container-high": "#ebe8dd",
        "on-tertiary-fixed-variant": "#872100",
        "on-secondary": "#ffffff",
        "primary-container": "#98a250",
        "surface-dim": "#dddad0",
        "text-main": "#4A4A4A",
        "error": "#ba1a1a",
        "sunset-accent": "#E45D36",
        "primary": "#5b6318",
        "surface-container": "#f1eee3",
        "on-surface": "#1c1c16",
        "tertiary": "#ab3510",
        "on-primary": "#ffffff",
        "background": "#fcf9ee",
        "surface-container-highest": "#e5e3d8",
        "on-background": "#1c1c16",
        "on-primary-container": "#313700",
        "on-primary-fixed": "#1a1e00",
        "secondary-container": "#f0e17f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb5a0",
        "tertiary-fixed": "#ffdbd1",
        "outline": "#787868",
        "inverse-primary": "#c3cd76",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#d6c868",
        "on-surface-variant": "#47483a",
        "on-tertiary-container": "#651600",
        "surface-tint": "#5b6318",
        "primary-fixed": "#dfea8f",
        "inverse-on-surface": "#f4f1e6",
        "on-primary-fixed-variant": "#434b00",
        "floral-green": "#98A250",
        "on-tertiary-fixed": "#3b0900",
        "outline-variant": "#c8c8b5",
        "surface-container-low": "#f6f4e9",
        "inverse-surface": "#31312a",
        "secondary": "#6a5f04",
        "tertiary-container": "#fe7047",
        "surface": "#fcf9ee",
        "on-secondary-fixed-variant": "#504700",
        "surface-variant": "#e5e3d8",
        "on-secondary-fixed": "#201c00",
        "on-secondary-container": "#6e6309",
        "surface-bright": "#fcf9ee",
        "on-error-container": "#93000a",
        "background-alt": "#FEFFDE",
        "primary-fixed-dim": "#c3cd76"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "element-gap": "1.5rem",
        "section-gap": "5rem",
        "container-padding": "2rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "body-lg": ["Indie Flower"],
        "headline-lg-mobile": ["Hurricane"],
        "meta-data": ["Work Sans"],
        "headline-lg": ["Hurricane"],
        "body-md": ["Indie Flower"],
        "section-title": ["Hurricane"],
        "display-romantic": ["Hurricane"],
        "label-caps": ["Work Sans"],
        "caveat": ["Caveat", "cursive"],
        "great-vibes": ["Great Vibes", "cursive"],
        "montserrat": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["20px", { "lineHeight": "30px", "fontWeight": "400" }],
        "headline-lg-mobile": ["40px", { "lineHeight": "48px", "fontWeight": "400" }],
        "meta-data": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "section-title": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
        "display-romantic": ["64px", { "lineHeight": "72px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
